#!/bin/sh

# neobundlePath="~/.vim/bundle/neobundle.vim"
# mkdir -p ~/.vim/bundle
# ln -sf ~/dotfiles/.vimrc ~/.vimrc
# ln -sf ~/dotfiles/.vim ~/.vim
ln -sf ~/dotfiles/.mac-local-provisioning ~/.mac-local-provisioning
ln -sf ~/dotfiles/.spacemacs ~/.spacemacs
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile

git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
