#!/bin/sh

mv ~/.gitconfig ~/dotfiles/
mv ~/.vimrc ~/dotfiles/
mv ~/.bash_profile ~/dotfiles

ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
