#!/bin/sh

neobundlePath="~/.vim/bundle/neobundle.vim"

mkdir -p ~/.vim/bundle

ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.vim ~/.vim

git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
